Repository symfony/webpack-encore-bundle, pull requests merged in 2022-07, with the labels that each got.

#185 [ci] fix flex plugin & legacy stimulus tests
  .github/workflows/ci.yml
  src/Dto/AbstractStimulusDto.php
  tests/IntegrationTest.php
Labels: Minor

#186 Stimulus: move deprecations from DTOs to filters/functions
  src/Dto/StimulusActionsDto.php
  src/Dto/StimulusControllersDto.php
  src/Dto/StimulusTargetsDto.php
  src/Twig/StimulusTwigExtension.php
Labels: Bug, Status: Reviewed

#188 Improve CONTRIBUTING.md & Psalm config
  .github/workflows/static.yml
  CONTRIBUTING.md
  psalm.xml
Labels: Minor, Status: Reviewed
